export const STUDENTS_6A = [
  'Álvarez Julio Thiago',
  'Angarita Rey Álvaro Andrés',
  'Cardona Marín Matías Andrés',
  'Díaz Díaz Hefzibá',
  'Gutiérrez Lobo Camila Andrea',
  'Hernández Gómez Jerónimo',
  'Londoño Guzmán Ana María',
  'Meza Mercado Juan Diego',
  'Montoya González Juan David',
  'Morales Villamizar Sarai Lisset',
  'Ortiz Comas Gabriela Sofía',
  'Patiño Peña Valery Michell',
  'Pérez Gayón Camilo',
  'Poblado Pallares María José',
  'Pulido Martínez Manuel José',
  'Quintero Chalarca Santiago',
  'Rincón Tarazona Mariana',
  'Ruiz Benavides Samuel Esteban',
  'Salom Marconi Isabella',
  'Suárez Barón Juliana',
  'Taboada Rivera María Sofía',
  'Urzola Salom Samuel Fernando'
];

export const STUDENTS_6B = [
  'Ávila Silva Miguel Ángel',
  'Correa Arias Esteban David',
  'Cristancho Martínez Izza Ninel',
  'Fonseca Granados Jerónimo',
  'Guevara Carreño Loren Victoria',
  'Lozano Velásquez Emilia',
  'Martínez Gélvez Mariana',
  'Meléndez Anaya Thomás Andrés',
  'Meza Viloria Juan José',
  'Muñoz Morales Lauren Alejandra',
  'Ortiz Rodríguez Ari Daniel',
  'Pérez Bermeo Giselle',
  'Pontón Sánchez Juan Diego',
  'Posada Arévalo Sofía',
  'Rojas Quintero Emmanuel',
  'Sánchez Noguera Rudin Daniel',
  'Silva Cubides Santiago',
  'Vanegas Quintana Salomé',
  'Velandia Meneses Matías',
  'Zárate Mercado Valeria'
];
